# Usar a imagem oficial do PostgreSQL
FROM postgres:15-alpine

# Variáveis de ambiente para configuração do banco de dados
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=escola_infantil

# Copiar o script SQL para o local de inicialização do PostgreSQL
COPY ./script.sql /docker-entrypoint-initdb.d/

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
